[package]
authors = ["Steve Klabnik <steve@steveklabnik.com>"]
name = "contributors"
version = "0.1.0"

[workspace]

[[bin]]
name = "contributors"
doc = false
[[bin]]
name = "populate"
path = "src/bin/populate.rs"
doc = false
[[bin]]
name = "update-commit-db"
path = "src/bin/update-commit-db.rs"
doc = false
[[bin]]
name = "new-release"
path = "src/bin/new-release.rs"
doc = false
[[bin]]
name = "the-big-red-button"
path = "src/bin/the-big-red-button.rs"
doc = false

[dependencies]
futures = "0.1.7"
reqwest = "0.2.0"
serde = "0.8.22"
serde_derive = "0.8.22"
serde_json = "0.8.4"
diesel = "0.9.0"
diesel_codegen = { version = "0.9.0", features = ["postgres"] }
dotenv = "0.8.0"
caseless = "0.1.2"
unicode-normalization = "0.1.0"
clap = "2.19.0"
slog = "1.4.1"
slog-term = "1.3.5"
regex = "0.2.1"

[dependencies.http]
path = "./http"

[dependencies.handlebars]
version = "0.24.1"
features = ["serde_type"]

[dependencies.hyper]
branch = "master"
git = "https://github.com/hyperium/hyper"
